version: '3.3'

services:
    web:
        build: ./django-container
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django-container/base_django/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
        - db
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=postgres_admin
        - POSTGRES_PASSWORD=postgres_passwd
        - POSTGRES_DB=django_postgres_dev

volumes:
    postgres_data: