version: '3.3'

services:
    web:
        build:
            context: ./django-container
            dockerfile: Dockerfile.prod
        command: gunicorn base_django.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        volumes:
            - ./django-container/base_django/frontend/:/home/app/web/frontend/
            - static_volume:/home/app/web/static
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/home/app/web/static
        depends_on:
            - web
volumes:
    postgres_data:
    static_volume: